### ISSUE TITLE
Integration broken in sensor.py

### ISSUE THREAD

**Issue by dkNeumann** [J-Lindvig/Flagdays_DK#1]
The last couple of days I get an error loading the integration:

Error while setting up flagdays_dk platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/flagdays_dk/sensor.py", line 46, in async_setup_platform
    entities.append(FlagDaysSensor(hass, coordinator, flagDays))
  File "/config/custom_components/flagdays_dk/sensor.py", line 55, in __init__
    self._state = flagDays._next_event['days_to_event']
KeyError: 'days_to_event'

Using latest 1.6. HA 2022.4.5 (issues was previously observed in version 2022.4.0 but then it has been working just before Easter Day).

**Comment by J-Lindvig** [comment]
I will look into it, thanks for reporting./Jacob18. apr. 2022 13.36 skrev dkNeumann ***@***.***>:
The last couple of days I get an error loading the integration:
Error while setting up flagdays_dk platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/flagdays_dk/sensor.py", line 46, in async_setup_platform
entities.append(FlagDaysSensor(hass, coordinator, flagDays))
File "/config/custom_components/flagdays_dk/sensor.py", line 55, in init
self._state = flagDays._next_event['days_to_event']
KeyError: 'days_to_event'
Using latest 1.6. HA 2022.4.5 (issues was previously observed in version 2022.4.0 but then it has been working just before Easter Day).

**Comment by J-Lindvig** [comment]
The fault has been found....

The integration is using an online API (https://sunrise-sunset.org/) to calculate sunrise/sunset in the future. The SSL certificate on this API is no longer valid.

A quick fix is to remove remove verification of the SSL on the request, but this gives mulitple errors in the log, but the integration works.

I will try to find another, and more durable, solution to these calculation.

**Comment by J-Lindvig** [comment]
I changed the URL on the API from https to plain http, this fixed the issue. Please update to v. 1.7.

I will see if the APIs certificate will update in the future.

**Comment by dkNeumann** [comment]
I works for me right now.

/Henrik

Get Outlook til Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by J-Lindvig** [comment]
Version 1.7?

**Comment by dkNeumann** [comment]
Yes. Just installed, restarted and I got Benediktes birthday come up.

/Henrik

Get Outlook til Android<https://aka.ms/AAb9ysg>
________________________________
